/* Generated By:JavaCC: Do not edit this line. LDIF_ParserConstants.java */
package com.google.code.nb_ldap_explorer.ldif.javacclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LDIF_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int UTF8_1 = 3;
  /** RegularExpression Id. */
  int UTF8_2 = 4;
  /** RegularExpression Id. */
  int UTF8_3 = 5;
  /** RegularExpression Id. */
  int UTF8_4 = 6;
  /** RegularExpression Id. */
  int UTF8_5 = 7;
  /** RegularExpression Id. */
  int UTF8_6 = 8;
  /** RegularExpression Id. */
  int SAFE_CHAR = 9;
  /** RegularExpression Id. */
  int SAFE_INIT_CHAR = 10;
  /** RegularExpression Id. */
  int SAFE_STRING = 11;
  /** RegularExpression Id. */
  int UTF8_CHAR = 12;
  /** RegularExpression Id. */
  int UTF8_STRING = 13;
  /** RegularExpression Id. */
  int BASE64_CHAR = 14;
  /** RegularExpression Id. */
  int BASE64_STRING = 15;
  /** RegularExpression Id. */
  int BASE64_UTF8_STRING = 16;
  /** RegularExpression Id. */
  int DNVALUESEP = 17;
  /** RegularExpression Id. */
  int DNNAMECOMPONENTSEP = 18;
  /** RegularExpression Id. */
  int NCATTRIBUTETYPEVALUESEP = 19;
  /** RegularExpression Id. */
  int LDIF_COMMENT = 20;
  /** RegularExpression Id. */
  int EOL = 21;
  /** RegularExpression Id. */
  int SPACE = 22;
  /** RegularExpression Id. */
  int VERSION = 23;
  /** RegularExpression Id. */
  int DN_START = 24;
  /** RegularExpression Id. */
  int CHANGETYPE = 25;
  /** RegularExpression Id. */
  int CONTROL = 26;
  /** RegularExpression Id. */
  int CONTROL_CRITICALITY = 27;
  /** RegularExpression Id. */
  int ADD = 28;
  /** RegularExpression Id. */
  int MODIFY = 29;
  /** RegularExpression Id. */
  int DELETE = 30;
  /** RegularExpression Id. */
  int REPLACE = 31;
  /** RegularExpression Id. */
  int MODRDN = 32;
  /** RegularExpression Id. */
  int NEWRDN = 33;
  /** RegularExpression Id. */
  int DELETEOLDRDN = 34;
  /** RegularExpression Id. */
  int NEWSUPERIOR = 35;
  /** RegularExpression Id. */
  int DN64_START = 36;
  /** RegularExpression Id. */
  int ATTVAL_SEP = 37;
  /** RegularExpression Id. */
  int ATTVAL_SEP_64 = 38;
  /** RegularExpression Id. */
  int ATTVAL_SEP_URL = 39;
  /** RegularExpression Id. */
  int END_OF_MOD = 40;
  /** RegularExpression Id. */
  int OPTION_SEP = 41;
  /** RegularExpression Id. */
  int ATTRIBUTE_TYPE_STRING = 42;
  /** RegularExpression Id. */
  int LDAP_OID = 43;
  /** RegularExpression Id. */
  int DN = 44;
  /** RegularExpression Id. */
  int VERSION_NUM = 45;
  /** RegularExpression Id. */
  int DELETEOLDRDN_YESNO = 46;
  /** RegularExpression Id. */
  int ATTVALUE = 47;
  /** RegularExpression Id. */
  int BASE64_ATTVALUE = 48;
  /** RegularExpression Id. */
  int URL = 50;
  /** RegularExpression Id. */
  int DN64_VALUE = 51;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DN64_VALUE_S = 1;
  /** Lexical state. */
  int ATTVALUE_S_URL = 2;
  /** Lexical state. */
  int ATTVALUE_S_64 = 3;
  /** Lexical state. */
  int ATTVALUE_S = 4;
  /** Lexical state. */
  int DELETEOLDRDN_S = 5;
  /** Lexical state. */
  int VERSION_S = 6;
  /** Lexical state. */
  int DN_S = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHA>",
    "<DIGIT>",
    "<UTF8_1>",
    "<UTF8_2>",
    "<UTF8_3>",
    "<UTF8_4>",
    "<UTF8_5>",
    "<UTF8_6>",
    "<SAFE_CHAR>",
    "<SAFE_INIT_CHAR>",
    "<SAFE_STRING>",
    "<UTF8_CHAR>",
    "<UTF8_STRING>",
    "<BASE64_CHAR>",
    "<BASE64_STRING>",
    "<BASE64_UTF8_STRING>",
    "\",\"",
    "\"+\"",
    "\"=\"",
    "<LDIF_COMMENT>",
    "<EOL>",
    "\" \"",
    "<VERSION>",
    "<DN_START>",
    "\"changetype\"",
    "\"control\"",
    "<CONTROL_CRITICALITY>",
    "\"add\"",
    "\"modify\"",
    "\"delete\"",
    "\"replace\"",
    "<MODRDN>",
    "\"newrdn\"",
    "\"deleteoldrdn\"",
    "\"newsuperior\"",
    "<DN64_START>",
    "<ATTVAL_SEP>",
    "<ATTVAL_SEP_64>",
    "<ATTVAL_SEP_URL>",
    "\"-\"",
    "\";\"",
    "<ATTRIBUTE_TYPE_STRING>",
    "<LDAP_OID>",
    "<DN>",
    "<VERSION_NUM>",
    "<DELETEOLDRDN_YESNO>",
    "<ATTVALUE>",
    "<BASE64_ATTVALUE>",
    "<token of kind 49>",
    "<URL>",
    "<DN64_VALUE>",
  };

}
